### ISSUE TITLE
커스텀 모듈 주소

### ISSUE THREAD

**Issue by youeh1** [juliakorea/talks#10]
안녕하세요

모듈 관련해서 하나 질문 드리고 싶어요 (또 수정....)

다른사람들이 올려 놓은 모듈을 Pkg를 이용하여 install한다는 것은 어떤 개념 인가요?
단지 복사해서 모듈 모여 있는 공간에 놓는 것인가요 아니면 뭔가 추가적인 액션이 들어가는건지요..

덧
c 함수를 불러서 줄리아로 코드만드는 것에 관심이 있는데 
혹시 참고할 만한 자료나 소스코드같은것을 공유해주실수 있을까요?
공부하는데 참고 했으면 좋겠습니다.
감사합니다.

**Comment by wookay** [comment]
줄리아 패키지 시스템은 아래 문서에 잘 나와 있구요
https://julialang.github.io/Pkg.jl/v1/

C 코드 호출은 Calling C and Fortran Code  이것부터
https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/

HDF5 패키지로 예를 들면,  패키지 소스에
https://github.com/JuliaIO/HDF5.jl/blob/master/src/HDF5.jl
`Libdl.dlopen`
`ccall`
을 부르는 부분 위주로 참고하세요.

조금 더 깊게 들어가자면
HDF5는 build시 HDF5_jll을 사용하게끔 deps/deps.jl에 코드를 생성합니다
https://github.com/JuliaIO/HDF5.jl/blob/master/deps/build.jl

보통 Yggdrasil 에 이러한 래퍼 패키지(_jll)를 등록합니다
https://github.com/JuliaPackaging/Yggdrasil/tree/master/H/HDF5

줄리아 레지스트리에는 HDF5_jll, HDF5이 아래와 같이 등록되어 있습니다
https://github.com/JuliaRegistries/General/tree/master/H/HDF5_jll
https://github.com/JuliaRegistries/General/tree/master/H/HDF5


Yggdrasil, JuliaRegistries에 등록하지 않아도 얼마든지
개인만의 패키지를 만들고 사용할 수 있습니다

**Comment by youeh1** [comment]
감사합니다 ㅎㅎ
