### ISSUE TITLE
변수에 관한 질문 

### ISSUE THREAD

**Issue by youeh1** [juliakorea/talks#11]
https://github.com/youeh1/julia_practice/blob/master/question-Copy1.ipynb 

안녕하세요 
variable의 scope에 관한 질문을 드리려고 합니다.

하나의 함수를 만들면서 
그 안에서 동작하는 변수들의 이름은 
함수밖에 있는 변수의 이름이랑 다르게 하는 것이 좋은 건가요?

어떤 함수를 만들다가 우연히 알게 된 이상한 점을 발견하고
링크 걸어둔 예시를 통해서 간단히 테스트를 하게 되었습니다.

첫번째 test 함수는 밖에서 정의 된 a를 argument pass 없이 출력을 하게 되고

두번째 test1함수는 a를 새로 100으로 정의한 후 출력을 하였습니다. 

세번째 함수 test2 는 이 둘을 합쳐서 실행을 해보았는데
제 예상은 10을 출력하고 그다음 100을 출력하는 건데
이상하게도 a가 정의 되지 않았다고 에러가 나오네요..
그나마 해석을 해보자면
함수내에서 a 가 initialization이 되면 밖에서 정의된 a는 무시가 되는 건가요?
둘다 a라고 지정을 했지만 이 둘은 같은것이 아닌 것 같은데..
왜 이런일이 생기는지 메모리 레벨에서 설명을 해주실 수있을까요?

이와 더불어서 전반적으로 함수를 작성 할때 주의해야 할 점이라던가
팁 같은것을 배울 수 있을까요?

감사합니다.

**Comment by wookay** [comment]
Scope of Variables 문제인데
`global` 키워드로 global 변수임을 알려주는 것을 추천합니다.

```julia
function test2()
    global a
    println("$a is from outside")
    
    a = 100
    println("$a is from inside")
end
```

Julia 1.5 에서는 soft scope를 기본으로 합니다
https://docs.julialang.org/en/v1.5-dev/manual/variables-and-scoping/

(Julia 1.4까지는 아래를 보면 됩니다)
https://docs.julialang.org/en/v1.4/manual/variables-and-scoping/

팁은 Performance Tips를 보면 무난할 것 같네요.
https://docs.julialang.org/en/v1.5-dev/manual/performance-tips/
