### ISSUE TITLE
어레이 트랜스 포즈

### ISSUE THREAD

**Issue by youeh1** [juliakorea/talks#12]
안녕하세요

매트랩으로 쓰여진 코드를 줄리아로 래퍼 하려고 하나씩 비교 하려고 매트랩 함수를 줄리아로 끌어다가 (MATLAB.jl 이용)
퓨어 줄리아 코드랑 비교 하는 작업을 하고 있습니다.

하나 발견한 점은 mxcall function이 트랜스포즈 된 어레이를 인식 못하는 것 같습니다.
ex>
1×10000 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:  -- target
간단한 매트랩 커스텀 펑션으로 길이를 리턴 하라고 만들면 1로 나와 버리네요

function b = myfunc1(x)
b = length(x);
end

mxcall(:myfunc1,1,target)
= 1.0

그래서 트랜스포즈 하고 나서 저런 형태가 아닌 그냥 어레이 형태로 바꾸려고 시도를 해보고 있는데
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/

이곳의 예시에서 처럼 시도를 하였으나
julia> A = [1 2im; -3im 4]
2×2 Array{Complex{Int64},2}:
 1+0im  0+2im
 0-3im  4+0im

julia> T = transpose(A)
2×2 Transpose{Complex{Int64},Array{Complex{Int64},2}}:
 1+0im  0-3im
 0+2im  4+0im

julia> copy(T)
2×2 Array{Complex{Int64},2}:
 1+0im  0-3im
 0+2im  4+0im

y(1:10)
a = Array(1:10)
10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
a
b= transpose(a)
1×10 LinearAlgebra.Transpose{Int64,Array{Int64,1}}:
 1  2  3  4  5  6  7  8  9  10
c = copy(b)
1×10 LinearAlgebra.Transpose{Int64,Array{Int64,1}}:
 1  2  3  4  5  6  7  8  9  10

이렇게 밖에 안되네요..

트랜스포즈를 하고 나서도 계속 Array{) 타입을 유지하게 할 수 있는 방법이 어떻게 있을까요??

**Comment by appleparan** [comment]
T가 Transpose Type이라면 조금 더 느려질 수 있지만,  `collect(T)`를 해보시죠.

**Comment by youeh1** [comment]
앗 감사합니다. 되네요
근데 타입이 {,2)로 나오는데 그럼
a[1,:]이런식으로 차원을 낮추면 될까요?

사실 확인만 하고 결과가 같다면 나중에 매트랩 함수는 쓰지 않을거라 속도는 상관 없겠지만서도요..

**Comment by appleparan** [comment]
그건 2차원이라 그런데, `length(collect(T))` 라고 하면 되지 않을까요
