### ISSUE TITLE
struct으로 생성한 인스턴스를 deepcopy했을 때 동작 질문이요

### ISSUE THREAD

**Issue by Codetre** [juliakorea/talks#13]
안녕하세요. 갓 줄리아에 입문한 초보입니다. 도서 "줄리아를 생각하다"의 15장 문제를 풀다가 이해가 안 가는 부분이 생겨 질문드립니다. 

```
struct Point
    x
    y
end

p1 = Point(1, 2)
p2 = deepcopy(p1)

@show p1 === p2  # true
```
-------------------------------------
위 코드에서 p1 === p2가 true임이 이해가 가질 않네요. deepcopy면 p1과 p2가 완전히 다른 메모리 주소를 가리키니 false라고 생각하는데, 왜 저런 결과를 내놓는 건가요?

**Comment by appleparan** [comment]
1. 우선 `===` 이 뭔지 살펴봅시다.

    [문서](https://docs.julialang.org/en/v1/base/base/#Core.:===)를 보시면 아시겠지만 

    > Determine whether x and y are identical, in the sense that no program could distinguish them. First the types of x and y are compared. If those are identical, mutable objects are compared by address in memory and immutable objects (such as numbers) are compared by contents at the bit level. This function is sometimes called "egal". It always returns a Bool value.

    라고 되어있습니다.  type이야 같을테니 말할 것도 없고, mutable object이면 메모리의 주소를, immutable object이면 그 내용을 비교한다고 되어있습니다.

2. 이제 그럼 immutable object인지 mutable object인지 확인하시면 됩니다. struct는 mutable일까요? 아니면 immutable일까요?
일반적으로 struct는 immutable입니다. [참고](https://docs.julialang.org/en/v1/manual/types/#Composite-Types)
왜냐하면, 생성된 이후에는 바꿀 수 없기 때문입니다.  

    [문서](https://docs.julialang.org/en/v1/manual/types/#Composite-Types)에도 
    > Composite objects declared with struct are immutable; they cannot be modified after construction.

    라고 되어있습니다. 따라서 주소가 아닌 내용만을 비교하면 되므로, true인 것입니다.

**Comment by Codetre** [comment]
@appleparan 감사합니다! 공식문서에 설명이 다 돼 있었네요;;
