### ISSUE TITLE
$ 이 포함된 문자열 인식 및 파싱?

### ISSUE THREAD

**Issue by youeh1** [juliakorea/talks#14]
안녕하세요

메세지를 스트링으로 저장하고 안에 있는 정보를 나중에 파싱하려고 하는데

ex = "Your market order to sell 1 share of NVDA was executed at an average price of $536.03 on January 20th, 2021 at 3:38 PM."
저기 달러 마크 때문에 문자열로 인식을 못하고 에러를 내 뱉네요..
syntax: invalid interpolation syntax: "$5"

Stacktrace:
 [1] top-level scope at In[3]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

주식 거래시 매 저런 문구가 날라오는데 텍스트 파일 같은데에 이걸 저장해서 (ctr cv?)
보유중인 주식 수익 계산을 해보려고 하고 있습니다.

흠 제가 생각 해본건 c 언어로 파싱하는 걸 만든 다음 줄리아에서 가져다가 쓰면 될까요
잘 안써봐서 기억은 잘 안나지만 $ 대신 %를 쓰니까 아마 에러는 안날거 같다는 생각이 들지만..

가장 간단한 방법은 복붙 할때 저기 달러 하나만 지우면 사실 되지만
줄리아 문법 내에서 혹시 해결이 가능 한지 여쭙고 싶습니다.

그리고 저런 메세지가 지멜이나 홈페이지 메세지 창에 업데이트가 되는데
이런 메세지가 나올때 자동으로 수집해서 파일로 저장 하고 싶은데
크롤링 뭐 이런 검색어로 찾아들어가면 될까요?

몇몇 키워드로 (줄리아 메일 크롤링 등등)으로 검색을 해봤지만 일단 초보의 목표는
데이터는 인간의 힘으로 얻고 계산 하는 간단한 프로그램을 작성해보는것 이 목표입니다.

감사합니다.

**Comment by appleparan** [comment]
이제서야 봤군요. `$`는 Julia String에서 [Interpolation](https://docs.julialang.org/en/v1/manual/strings/#string-interpolation), 즉 변수에 있는 String으로 대치되도록 하는 기능을 지원하는 문자열입니다. 즉 일반적인 문자라고 인식이 안되는 거죠. 따라서 일반적인 문자로 인식해주는 절차가 필요합니다.

방법은 두 가지가 있습니다.

1. `$` 대신 `\$`로 써보세요.
```
ex = "Your market order to sell 1 share of NVDA was executed at an average price of \$536.03 on January 20th, 2021 at 3:38 PM."
```
2.  원래 문장 앞에 raw를 붙이시면 됩니다.  이를 [Raw String Literals](https://docs.julialang.org/en/v1/manual/strings/#man-raw-string-literals) 이라고 합니다.
```
ex = raw"Your market order to sell 1 share of NVDA was executed at an average price of $536.03 on January 20th, 2021 at 3:38 PM."
```

그런데 질문하신 내용을 보면, 어디서 받아오시는거같은데 뭘로 받아오시는건가요?

**Comment by youeh1** [comment]
답변 감사합니다.

해당 문구는 받은 메일에 나와있는 화면 문구를 복붙 한 것입니다.

복붙을 한 상태에서 텍스트 파일에다가 저장한다음 (한줄로)
f = open("stock.txt")
lines = readlines(f)
close(f)
요렇게 파일 읽기로 읽어들이면 자동으로 $를 \$로 처리해서 저장해줘서 제가 제기 했던 문제는 해결 됬네요
위에 예시로 든건 줄리아에 바로 문자열로 저장 할때 (주피터노트북) 생긴 문제 였구요

그리고 string이 아니라 char로 읽으면 $도 바로 읽혀지는걸 발견 했습니다 ㅎㅎ
문자는 interpolation할 필요가 없으니 당연하겠지만요 ㅎㅎ
