### ISSUE TITLE
초보적인 질문 하나 부탁드릴게요

### ISSUE THREAD

**Issue by youeh1** [juliakorea/talks#6]
안녕하세요

줄리아 포함해서 코딩에 아직 익숙 하지 않은 초보자입니다.

한가지 여쭤보고 싶은것은

예를 들어 c언어에서는 변수를 직접 입력하는 것 대신
포인터를 이용하여 원하는 변수의 주소를 특정 함수에  집어넣어서
그 함수 안에서 계산을 하고 함수가 종료되고 나서도 해당 변수의 값이 바뀐채로 그대로 남아 있게 하는 것이 가능 한데요.

줄리아에서 이걸 구현하는데 잘 안되서..
찾아 보면 포인터 같은 기능을 하는것도 있는 거 같기도한데.. Ptr{void}?

혹시 줄리아에서도 가능하다면 
간단한 예제와 함께 설명 부탁드려도 될까요??

감사합니다.

**Comment by wookay** [comment]
`Ref`(https://docs.julialang.org/en/v1.4-dev/base/c/#Core.Ref) 쓰면 될 듯요.

```julia
julia> a = Ref(1)
Base.RefValue{Int64}(1)

julia> f(x) = x[] += 1
f (generic function with 1 method)

julia> f(a)
2

julia> a
Base.RefValue{Int64}(2)

julia> a[]
2
```

**Comment by youeh1** [comment]
오 감사합니다! 제가 찾던거네요 ㅎㅎ
